#!/bin/bash

# Define some common variables - those can be overwritten by 
# environment variables. Currently only x86 is supported. Thus
# to build for 32 Bit instead of 64 Bit, export some variables
# before building:
#
# This matches i686 - Pentium II, 32 bit x86
#
# export TINYTARGET=i386-linux-musl
# export TINYCPU=i686
# 
# This matches Raspberry Pi - currently under development
#
# export TINYTARGET=arm-linux-musleabihf 
# export TINYARCH=arm
# export TINYCPU=armv6
# export CLFS_FPU=vfp
# export CLFS_FLOAT=hard
# export TINYBUILDDIR=/mnt/archiv/TinyCrossBuildPi

CLFS=/mnt/archiv/TinyCrossBuild
if [ -n "$TINYBUILDDIR" ] ; then
	CLFS="$TINYBUILDDIR"
fi
export CLFS
SRCDIR=${CLFS}/src
if [ -n "$TINYSRCDIR" ] ; then
	SRCDIR="$TINYSRCDIR"
fi
export SRCDIR
export CLFS_TARGET=x86_64-linux-musl 
if [ -n "$TINYTARGET" ] ; then
	export CLFS_TARGET="$TINYTARGET"
fi
export CLFS_CPU=k8
if [ -n "$TINYCPU" ] ; then
	export CLFS_CPU="$TINYCPU"
fi
export CLFS_ARCH="x86"
if [ -n "$TINYARCH" ] ; then
	export CLFS_ARCH="$TINYARCH"
	if [ "$TINYARCH" = arm ] ; then
		if [ -z "$CLFS_FPU" ] ; then
			echo '***> FAILED. Please provide CLFS_FPU to specify your floating point unit!'
			exit 1
		fi
		if [ -z "$CLFS_FLOAT" ] ; then
			echo '***> FAILED. Please provide CLFS_FLOAT to specify your floating point type!'
			exit 1
		fi
	fi
fi
